name: Census Deployment Environment

# Triggers for the workflow
on:
    # Manual trigger using the workflow_dispatch event
    workflow_dispatch:
    
    # Automatic trigger on push events to the main branch
    push:
      branches:
        - main
# defaults:
#     run:
#         working-directory: ../

jobs:
    # Continuous Integration job
    ci_for_Prod:
        runs-on: ubuntu-latest
        
 
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
  
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.8'

            - name: Install dependencies
              run: |
                pip install -r requirements.txt
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1
            - name:  Login to Amazon ECR
              id: ecr
              uses: aws-actions/amazon-ecr-login@v2
        
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        
            - name: Build the docker image
              env:
                ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
                ECR_REPOSITORY: ${{secrets.ECR_REPOSITORY}}
              run: |
                  docker build -t ECR_REGISTRY/ECR_REPOSITORY:latest ../
                  docker push ECR_REGISTRY/ECR_REPOSITORY:latest
            
            - name: Update Lambda function with the latest Docker image for production
              env:
                ECR_REGISTRY: ${{ steps.ecr.outputs.registry }}
              run: |
                  aws lambda update-function-code --function-name census --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest
                  